version: '3.7'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agents
    deploy:
      mode: global

  frontend:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify --no-analytics
    volumes:
      - /media/share/portainer:/data
    networks:
      - agents
      - proxy
    deploy:
      labels:
        traefik.port: 9000
        traefik.frontend.rule: "Host:portainer.domain.com"

networks:
  agents:
    driver: overlay
    attachable: true
  proxy:
    external: true
